data<-fread("household_power_consumption.txt")
data<-as.data.frame(data)
data$Date<-as.Date.character(data$Date, c("%d/%m/%Y"))
data<-subset.data.frame(data, data$Date==c("2007-02-01","2007-02-02"))
data$Global_active_power<-as.numeric(data$Global_active_power)
data$Global_reactive_power<-as.numeric(data$Global_reactive_power)
data$Global_intensity<-as.numeric(data$Global_intensity)
data$Sub_metering_1<-as.numeric(data$Sub_metering_1)
data$Sub_metering_2<-as.numeric(data$Sub_metering_2)
data$Sub_metering_3<-as.numeric(data$Sub_metering_3)
data$datetime<-as.POSIXct(paste(data$Date, data$Time), format="%Y-%m-%d %H:%M:%S")
png("plot3.png", width= 480,height=480)
plot(data$datetime, data$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
points(data$datetime, data$Sub_metering_2, type="l", col="red")
points(data$datetime, data$Sub_metering_3, type="l",col="blue")
legend("topright", lty=c(1,1,1),lwd=c(2,2,2), col=c("black", "red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()